version: '2'
services:
  mysql:
    image: mysql:8.0.17
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_ROOT_HOST=%
    volumes:
    - ../../mysql/docker/shared:/app/shared
    command: --secure-file-priv=/app/shared
  pdi:
    build: .
    image: pdi-ce
    environment:
    - DISPLAY=$DISPLAY
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - ./shared:/shared
    links:
    - mysql